-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8AmxIhyNmcfJuxJe
UvZfhOVIJEFjEWX1pvK6jM6QxZigCgYIKoZIzj0DAQehRANCAAQC2bKirN0coiPL
eB5eQx1dZ88JkP/VCehDlnBU3DSH899x6k1OLLezVif/esFE+cYFYqjfr2wfmM4B
Czds6Vl3
-----END PRIVATE KEY-----