const APP_STRINGS = {
  'faq_question_1': 'How does the marketplace work?',
  'faq_answer_1':
      'Our marketplace connects buyers and sellers directly. List your discs with photos and details, or browse available discs with advanced filters.',
  'faq_question_2': 'Can I list discs for free?',
  'faq_answer_2': 'Yes! all listings are completely free.',
  'faq_question_3': 'How do I track my scores?',
  'faq_answer_3':
      'Simply open the app during your round, select your course, and input scores as you play. The app automatically calculates statistics and tracks your progress.',
  'faq_question_4': 'Is this another subscription app?',
  'faq_answer_4': 'No! There are no subscription and no in-app purchases. (And it is not part of our strategy to add it in the future)',
  'privacy_policy': 'Privacy Policy',
  'privacy_policy_0_0_1':
      'ACEMAKERS DEVELOPMENT PTE. LTD ("Company," "we," "us," or "our") operates Capty, a disc golf platform that helps users track their progress, connect with players, and buy/sell discs. This Privacy Policy explains how we collect, use, and protect your data.',
  'privacy_policy_0_0_2': 'By using Capty, you agree to this Privacy Policy. If you do not agree, please do not use the app.',
  'privacy_policy_1': 'General Information',
  'privacy_policy_1_0_1': 'Company Name: ACEMAKERS DEVELOPMENT PTE. LTD',
  'privacy_policy_1_0_2': 'Address: 111 North Bridge Road, #20-05, Peninsula Plaza, Singapore 179098',
  'privacy_policy_1_0_3': 'Registration Number (UEN): 202509691G',
  'privacy_policy_1_0_4': 'Contact Email: casper@acemakers.sg',
  'privacy_policy_1_0_5': 'Data Protection Officer: Casper Gronbjerg',
  'privacy_policy_2': 'Data Collection & Usage',
  'privacy_policy_2_1': 'Personal Data We Collect',
  'privacy_policy_2_1_1': 'When you use Capty, we may collect the following personal data:',
  'privacy_policy_2_1_2': 'User Account Information: Name, email, phone number, profile image',
  'privacy_policy_2_1_3': 'Performance & Gameplay Data: PDGA number, PDGA rating, tournament participation',
  'privacy_policy_2_1_4': 'Marketplace Data: Disc listings, descriptions, images uploaded for sales ads',
  'privacy_policy_2_1_5': 'Club & Social Data: Club memberships, event participation, user interactions',
  'privacy_policy_2_1_6': 'Login Credentials: Authentication via Google, Apple, or other login methods',
  'privacy_policy_2_1_7':
      'Location Data: Real-time GPS-based location used for course recommendations and local player connections (we do not store this data)',
  'privacy_policy_2_1_8': 'We do not collect health, fitness, or biometric data.',
  'privacy_policy_2_2': 'Financial Data (Future Implementation)',
  'privacy_policy_2_2_1':
      'In the future, Capty will introduce features that allow users to manage payments and credits between buyers and sellers in the marketplace. When implemented, this section will be updated to reflect how payment details are processed and stored.',
  'privacy_policy_2_3': 'Third-Party Services We Integrate With',
  'privacy_policy_2_3_1': 'Capty integrates with the following services to enhance the user experience:',
  'privacy_policy_2_3_2': 'Twilio (for SMS verification and notifications)',
  'privacy_policy_2_3_3': 'Firebase (for database storage and user authentication)',
  'privacy_policy_2_3_4': 'Google & Apple (for single sign-on login methods)',
  'privacy_policy_2_3_5': 'Shopify (for webshop integration in the disc marketplace)',
  'privacy_policy_3': 'Data Storage & Security',
  'privacy_policy_3_1': 'Where We Store Your Data',
  'privacy_policy_3_1_1': 'User data is securely stored on Digital Ocean servers with industry-standard encryption.',
  'privacy_policy_3_2': 'How Long We Retain Your Data',
  'privacy_policy_3_2_1': 'We retain user data until the user chooses to delete it.',
  'privacy_policy_3_3': 'How We Protect Your Data',
  'privacy_policy_3_3_1': 'We follow industry best practices, including:',
  'privacy_policy_3_3_2': 'Encryption: Data is encrypted both in transit and at rest.',
  'privacy_policy_3_3_3': 'Access Control: Only authorized personnel have access to sensitive data.',
  'privacy_policy_3_3_4': 'Monitoring: We continuously monitor for security threats and vulnerabilities.',
  'privacy_policy_3_4': 'How You Can Delete Your Data',
  'privacy_policy_3_4_1': 'You have two ways to delete your data:',
  'privacy_policy_3_4_2': 'Request via Support: Email us at casper@acemakers.sg to request deletion.',
  'privacy_policy_3_4_3': 'Self-Deletion via Web Admin: Log into the Capty web admin and initiate data deletion manually.',
  'privacy_policy_4': 'User Permissions & Third-Party Sharing',
  'privacy_policy_4_1': 'Who We Share Data With',
  'privacy_policy_4_1_1':
      'Capty does not sell or share user data with third-party advertisers. However, we do retrieve public PDGA data to allow users to compare rankings and track performance.',
  'privacy_policy_4_2': 'Personalized Ads',
  'privacy_policy_4_2_1': 'We do not display personalized ads based on user data.',
  'privacy_policy_4_3': 'Permissions Required',
  'privacy_policy_4_3_1': 'To provide full functionality, Capty requests the following permissions:',
  'privacy_policy_4_3_2': '📍 Location Data – Used in real-time for course recommendations and finding nearby players. (Not stored)',
  'privacy_policy_4_3_3': '📸 Camera & Photos – Used to upload images of discs when creating marketplace listings.',
  'privacy_policy_5': 'User Rights & Compliance',
  'privacy_policy_5_1': 'Your Rights Under GDPR (Europe)',
  'privacy_policy_5_1_1': 'Capty complies with GDPR, giving you the right to:',
  'privacy_policy_5_1_2': 'Access the personal data we store about you',
  'privacy_policy_5_1_3': 'Correct inaccurate or outdated information',
  'privacy_policy_5_1_4': 'Request deletion of your account and associated data',
  'privacy_policy_5_2': 'Your Rights Under CCPA (California)',
  'privacy_policy_5_2_1': 'Since Capty does not sell user data, there is no need for an opt-out mechanism under CCPA.',
  'privacy_policy_5_3': "Children's Privacy (COPPA Compliance)",
  'privacy_policy_5_3_1': 'Capty is not designed for children under 13, and we do not knowingly collect data from minors.',
  'privacy_policy_6': 'Privacy Policy Updates & Notifications',
  'privacy_policy_6_0_1': 'If we make any significant changes to this Privacy Policy, we will notify users by:',
  'privacy_policy_6_0_2': 'Posting an update on our website',
  'privacy_policy_6_0_3': 'Sending an in-app notification',
  'privacy_policy_6_0_4': 'We encourage users to review this policy periodically.',
  'privacy_policy_7': 'Contact Information for Privacy Concerns',
  'privacy_policy_7_0_1': 'If you have any questions or concerns regarding this Privacy Policy, you may contact us at:',
  'privacy_policy_7_0_2': '📧 Email: casper@acemakers.sg',
  'privacy_policy_7_0_3': '👤 Data Protection Officer: Casper Gronbjerg',

  'terms_and_conditions': 'Terms & Conditions',
  'terms_conditions_0_0_1':
      'Welcome to Capty, a disc golf platform operated by ACEMAKERS DEVELOPMENT PTE. LTD ("Company," "we," "us," or "our"). By using Capty, you agree to abide by these Terms and Conditions.',
  'terms_conditions_0_0_2': 'If you do not agree with these terms, please do not use the app.',
  'terms_conditions_1': 'General Information',
  'terms_conditions_1_0_1': 'Company Name: ACEMAKERS DEVELOPMENT PTE. LTD',
  'terms_conditions_1_0_2': 'Address: 111 North Bridge Road, #20-05, Peninsula Plaza, Singapore 179098',
  'terms_conditions_1_0_3': 'Registration Number (UEN): 202509691G',
  'terms_conditions_1_0_4': 'Legal Contact Email: casper@acemakers.sg',
  'terms_conditions_1_0_5': 'Jurisdiction: This agreement is governed by the laws of Singapore.',
  'terms_conditions_2': 'User Accounts & Responsibilities',
  'terms_conditions_2_1': 'Eligibility',
  'terms_conditions_2_1_1': 'You must be at least 13 years old to use Capty.',
  'terms_conditions_2_1_2': 'Users must verify their identity via phone number and OTP authentication.',
  'terms_conditions_2_2': 'User Conduct & Platform Rules',
  'terms_conditions_2_2_1': 'By using Capty, you agree not to:',
  'terms_conditions_2_2_2': '✅ Provide false information when updating club or course data (multiple violations may lead to suspension).',
  'terms_conditions_2_2_3': '✅ Misuse the marketplace for fraudulent or misleading sales.',
  'terms_conditions_2_2_4': '✅ Scrape data from the website or app.',
  'terms_conditions_2_2_5': '✅ Fail to follow through on agreements with other Capty users.',
  'terms_conditions_2_2_6':
      '🚫 Hate speech, discrimination, harassment, or offensive behavior based on culture, gender, sexual orientation, or religion is strictly prohibited.',
  'terms_conditions_2_3': 'Account Suspension & Termination',
  'terms_conditions_2_3_1':
      'Capty reserves the right to suspend or terminate accounts if users violate these terms, engage in fraudulent behavior, or remain inactive for extended periods.',
  'terms_conditions_2_4': 'Account Recovery',
  'terms_conditions_2_4_1': 'If you lose access to your account, you must contact support for assistance.',
  'terms_conditions_2_5': 'Account Deletion',
  'terms_conditions_2_5_1': 'Users can delete their accounts by:',
  'terms_conditions_2_5_2': 'Using the web admin panel',
  'terms_conditions_2_5_3': 'Requesting deletion via support at casper@acemakers.sg',
  'terms_conditions_3': 'Payments & Transactions (Marketplace Rules)',
  'terms_conditions_3_1': 'Payment Processing',
  'terms_conditions_3_1_1': 'Capty will process transactions via Mangopay, a third-party payment provider.',
  'terms_conditions_3_1_2':
      'Capty will introduce a 10% transaction fee starting January 2026, once payment and shipping options are enabled.',
  'terms_conditions_3_2': 'Marketplace Responsibility',
  'terms_conditions_3_2_1': 'Capty will process transactions via Mangopay, a third-party payment provider.',
  'terms_conditions_3_2_2':
      'Capty will introduce a 10% transaction fee starting January 2026, once payment and shipping options are enabled.',
  'terms_conditions_3_3': 'Buyer Protection & Refunds',
  'terms_conditions_3_3_1': 'If a user receives a wrong disc, they must resolve the issue directly with the seller.',
  'terms_conditions_3_3_2':
      r'If a buyer does not receive their disc, Capty provides buyer protection up to $30 USD (200 DKK) under these conditions.',
  'terms_conditions_3_3_3': 'The buyer must provide official documentation from the shipping company proving the package was lost.',
  'terms_conditions_3_3_4': 'Capty will process the refund under its 10% fee coverage policy.',
  'terms_conditions_4': 'User-Generated Content & Community Guidelines',
  'terms_conditions_4_1': 'Allowed Content',
  'terms_conditions_4_1_1': 'Users may upload:',
  'terms_conditions_4_1_2': '✅ Disc sales ads, marketplace listings',
  'terms_conditions_4_1_3': '✅ Messages, comments, and reviews',
  'terms_conditions_4_1_4': '✅ Leaderboard & performance data',
  'terms_conditions_4_2': 'Restricted Content',
  'terms_conditions_4_2_1': '🚫 Hate speech, illegal sales, spam, offensive images, or any form of harassment is strictly prohibited.',
  'terms_conditions_4_3': 'Ownership of Uploaded Content',
  'terms_conditions_4_3_1': 'Capty owns all content uploaded to the platform.',
  'terms_conditions_4_3_2': 'Users do not retain ownership of their listings, reviews, or messages.',
  'terms_conditions_4_3_3': 'Capty does not have permission to use uploaded images for marketing purposes.',
  'terms_conditions_4_4': 'Content Removal',
  'terms_conditions_4_4_1':
      "Capty reserves the right to remove any content that violates these terms, contains misleading information, or disrupts the platform's integrity.",
  'terms_conditions_5': 'Disclaimers & Liabilities',
  'terms_conditions_5_1': 'Liability Disclaimer',
  'terms_conditions_5_1_1': 'Capty is not responsible for damages caused by incorrect data, disputes between users, or technical errors.',
  'terms_conditions_5_1_2':
      'Marketplace listings and leaderboard rankings are provided "as-is", and Capty cannot guarantee their accuracy.',
  'terms_conditions_5_2': 'Technical Support',
  'terms_conditions_5_2_1': 'Users experiencing bugs, crashes, or account issues can contact support',
  'terms_conditions_5_2_2': 'Via the Capty app',
  'terms_conditions_5_2_3': 'Through the web admin panel',
  'terms_conditions_5_2_4': 'On the Capty website',
  'terms_conditions_6': 'Service Availability & Modifications',
  'terms_conditions_6_1': 'Right to Modify or Discontinue',
  'terms_conditions_6_1_1': 'Capty reserves the right to modify, suspend, or shut down any part of the platform at any time.',
  'terms_conditions_6_1_2': 'Capty is not liable for any damages resulting from service downtime or disruptions.',
  'terms_conditions_7': 'Changes to the Terms & Conditions',
  'terms_conditions_7_0_1': 'Any changes to these Terms will be announced via:',
  'terms_conditions_7_0_2': 'Website notifications',
  'terms_conditions_7_0_3': 'In-app alerts',
  'terms_conditions_7_0_4': 'Continued use of Capty after updates means you accept the new terms.',
  'terms_conditions_8': 'Contact & Legal Inquiries',
  'terms_conditions_8_0_1': 'For any legal questions or disputes, contact us at:',
  'terms_conditions_8_0_2': '📧 Email: casper@acemakers.sg',
  'terms_conditions_8_0_3': '📍 Company: ACEMAKERS DEVELOPMENT PTE. LTD',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'select_your_country': 'Select Your Country',
  'search_your_country': 'Search your country',
  'get_started': 'Get Started',
  'compete': 'Compete',
  'compare': 'Compare',
  'connect': 'Connect',
  'back': 'Back',
  'next': 'Next',
  'verify_your_phone': 'Verify your phone',
  'please_enter_the_4_digit_code_sent_as_a_text_message_to': 'Please enter the 4 digit code sent as a \ntext message to',
  'did_not_get_the_code': 'Didn’t get the code?',
  'resend_code': 'Resend code',
  'set_profile': 'Set profile',
  'fill_in_your_information_below': 'Fill in your information below',
  'ex': 'ex',
  'john_doe': 'John Doe',
  'are_you_a_member_of_a_club': 'Are you a member of a club?',
  'tree_line_tossers': 'Tree Line Tossers',
  'udisc_username': 'Udisc username',
  'are_you_a_registered_pdga_member': 'Are you a registered PDGA member?',
  'pdga_number': 'PDGA number',
  'please_write_your_club_name': 'Please write your club name',
  'please_write_your_udisc_username': 'Please write your udisc username',
  'please_write_your_pdga_number': 'Please write your pgda number',
  'club_name': 'Club name',
  'upload_profile_photo': 'Upload profile photo',
  'please_insert_a_picture_for_a_better_experience': 'Please insert a picture for a\nbetter experience',
  'cancel_photo': 'Cancel Photo',
  'upload_new': 'Upload New',
  'sign_in': 'Sign in',
  'phone_number': 'Phone-number',
  'agree_with': 'Agree with',
  'please_accept_our_terms_and_conditions': 'Please accept our terms and conditions',
  'please_write_your_name': 'Please write your name',
  'please_write_your_email_address': 'Please write your email address',
  'please_write_a_valid_email_address': 'Please write a valid email address',
  'please_write_your_phone_number': 'Please write your phone number',
  'digit': 'digit',
  'please_enter_your_verification_code': 'Please enter your verification code',
  'verification_code_must_be_4_digit': 'Verification code must be 4 digit',
  'please_write_your_address': 'Please write your address',
  'select_an_option': 'Select an Option',
  'take_a_photo': 'Take a Photo',
  'upload_from_gallery': 'Upload from Gallery',
  'edit_photo': 'Edit Photo',
  'done': 'Done',
  'spam': 'Spam',
  'marketing': 'Marketing',
  'useless_info': 'Useless info',
  'your_pdga_rating_is_updated': 'Your PDGA rating is updated',
  'a_club_member_makes_an_ace': 'A club member makes and ACE',
  'we_have_found_your_dream_disc_in_the_marketplace': 'We have found your dream disc in the marketplace',
  'why_say_yes_to_notifications_from_us': 'Why say yes to notifications from us?',
  'you_will_only_get_notifications_when': 'You will only get notifications when',
  'you_will_not_get_notifications_with': 'You will not get notifications with',
  'in_your_setting_area_you_will_always_be_able_to_turn_notifications_on_and_off':
      'In your setting area, you will always be able to turn notifications on and off',
  'allow': 'Allow',
  'do_not_allow': "Don't Allow",
  'see_used_discs_for_sale_close_to_where_you_are': 'See Used discs for sale close to where you are',
  'connect_with_disc_golfers_in_your_area_when_you_travel': 'Connect with Disc golfers in your area when you travel',
  'notify_you_if_you_are_in_close_proximity_of_a_great_course': 'Notify you if you are in close proximity of a great course',
  'sharing_with_third_party_where_you_are': 'Sharing with third party where you are',
  'saving_any_history_of_your_location': 'Saving any history of your location',
  'purposes_that_has_no_value_for_you': 'Purposes that has NO value for you',
  'why_say_yes_to_tracking_location': 'Why say yes to tracking location?',
  'you_will_get_these_options': 'You will get these options',
  'we_will_not_use_your_location_for': 'We will not use your location for',
  'in_your_setting_area_you_will_always_be_able_to_turn_location_on_and_off':
      'In your setting area, you will always be able to turn location tracking on and off',
  'are_you_a_disc_member': 'Are you a Udisc member?',

  'clubs_close_to_you': 'Clubs close to you',
  'members': 'members',
  'member': 'member',
  'km': 'km',
  'write_in_club_thread': 'Write in club thread',
  'sorry_we_cant_show_you_the_nearest_events':
      'Sorry, we cant show you the nearest events to your location as you are not sharing your location with us',
  'share_location': 'Share location',
  'n/a': 'N/A',
  'club_joined': 'Club Joined',
  'join_club': 'Join Club',
  'new_messages': 'New messages',
  'sales_ads': 'sales ads',
  'upcoming_tournaments': 'upcoming tournaments',
  'add_to_wishlist': 'Add to wishlist',
  'disc_name': 'Disc name',
  'manufacture': 'Manufacture',
  'disc_type': 'Disc type',
  'plastic': 'Plastic',
  'select_plastic': 'Select plastic',
  'notes': 'Notes',
  'write_notes_here': 'Write notes here',
  'this_disc_has_been_added_to_your_wishlist': 'This disc has been added to your wishlist',
  'your_notification_is_off_so_we_cant_notify':
      'Your notification is off. so we can’t notify you if we find a match with this discs. So if you want to notify by us please turn on your notification.',
  'allow_notifications': 'Allow notifications',
  'exit_capty': 'Exit Capty',
  'yes_exit': 'Yes, Exit',
  'no_stay': 'No, Stay',
  'as_a_manager_you_will_be_able_to': 'As a manager you will be able to',
  'currently_the_club_admins_are': 'Currently the club admins are',
  'there_are_currently_no_admins_of_this_club': 'There are currently no admins of this club',
  'go_to_web_admin': 'GO TO WEB ADMIN',
  'course_management': 'Course Management',
  'pick_a_color': 'Pick a color',
  'do_you_want_to_be_admin_for': 'Do you want to be admin for',
  'delete_account': 'Delete Account',
  'delete_account_description': 'Are you sure you want to delete your account? All your data will be lost forever',
  'yes_delete': 'Yes, Delete',
  'no_keep': 'No, Keep',
  'disc_details': 'Disc Details',
  'zoom': 'Zoom',
  'reset': 'Reset',
  'rotation': 'Rotation',
  'preview': 'Preview',
  'image_corrupted_please_try_again': 'Image corrupted!! Please try again!',
  'preview_image': 'Preview Image',
  'okay': 'Okay',
  'leaving_so_soon': 'Leaving so soon',
  'logout_description': 'Are you sure you want to log out from your account? You can login anytime.',
  'yes_logout': 'YES, LOGOUT',
  'logging_out': 'Logging Out',
  'sign_out': 'Sign Out',
  'my_profile': 'My Profile',
  'friends_cardmates': 'Friends/Cardmates',
  'course_manager': 'Course manager',
  'club_manager': 'Club manager',
  'suggest_a_feature': 'Suggest a feature',
  'report_a_problem': 'Report a problem',
  'faq': 'Faq',
  'settings': 'Settings',
  'clubs': 'Clubs',
  'club': 'Club',
  'select_a_date': 'Select a Date',
  'Please_select_the_day_after': 'Please select the day after',
  'no_country_found': 'No Country Found',
  'no_countries_available_now_please_tray_again_later': 'No countries available now! Please tray again later.',
  'you_are_all_set': 'You’re all set',
  'tell_me_more': 'Tell Me More',
  'can_we_search_for_disc_golf_clubs_using_your_current_location': 'Can we search for Discgolf clubs using your current location?',
  'we_would_like_to_use_your_location_to_search_for_disc_golf_clubs_in_your_area':
      'We would like to use your location to search for Disc golf clubs in your area',
  'we_have_found_these_clubs': 'We have found these clubs',
  'are_you_a_member_in_any_of_these_clubs': 'Are you a member in any of these clubs?',
  'my_club_is_not_here': 'My club is not here',
  'i_am_not_member_of_a_disc_golf_club': 'I am not member of a disc golf club',
  'do_not_see_your_country': "Don't see your country?",
  'join_our_waitlist': 'Join our waitlist',
  'join': 'Join',
  'profile': 'Profile',
  'pdga_rating': 'PDGA Rating',
  'club_points': 'Club points',
  'your_account_has_been_created': 'Your account has been created!',
  'go_to_dashboard': 'Go To Dashboard',
  'redirecting_to_your_homepage': 'Redirecting to your homepage',
  'delete_conversations': 'Delete Conversations?',
  'delete_conversation_description':
      'Once deleted, you will lose all your chat history in this conversation. Are you sure you want to delete this conversation?',
  'contact_seller': 'Contact Seller',
  'type_your_message_here': 'Type your message here',
  'your_disc_golf_club_has_been_created': 'Your disc golf club has been created.',
  'please_share_this_link_with_your_club_members_so_they_can_join_the_club':
      'Please share this link with your club members, so they can join the club',
  'link_for_the_club': 'Link for the club',
  'club_maintenance': 'Club Maintenance',
  'club_settings': 'Club Settings',
  'schedule_event': 'Schedule Event',
  'join_event': 'Join Event',
  'share': 'Share',
  'about_this_game': 'About this game',
  'comments': 'Comments',
  'type_here': 'Type here',
  'post_comment': 'Post Comment',
  'please_write_your_comment': 'Please write your comment',
  'post_your_comment': 'Post your comment',
  'write_your_comment_here': 'Write your comment here',
  'no_course_available_in_this_club': 'No course available in this club',
  'schedule_an_event': 'Schedule an event',
  'event_title': 'Event Title',
  'disc_golf_championship': 'Disc Golf Championship',
  'date': 'Date',
  'dd-mm-yyyy': 'DD-MM-YYYY',
  'time': 'Time',
  'hh:mm': 'HH:MM',
  'course': 'Course',
  'mastering_disc_golf': 'Mastering Disc Golf',
  'note': 'Note',
  'this_event_is_only_for_club_members': 'This event is only for club members',
  'please_write_the_title_of_the_event': 'Please write the title of the event',
  'please_write_the_date_of_the_event': 'Please select the date of the event',
  'please_write_the_time_of_the_event': 'Please select the time of the event',
  'please_write_a_note_for_this_event': 'Please write a note for this event',
  'club_event': 'Club Event',
  'club_event_details': 'Club event Details',
  'participants': 'Participants',
  'no_comments_available_now': 'No comments available now!',
  'communicate': 'Communicate',
  'home_course': 'Home course',
  'club_action': 'Club Action',
  'upcoming_events': 'Upcoming Events',
  'discs_for_sale_in_this_club': 'Discs for sale in this club',
  'view_more': 'View More',
  'url_not_found_please_try_again_later': 'Url not found! Please try again later',
  'create_your_club': 'Create Your Club',
  'step': 'Step',
  'storm_chasers': 'Storm Chasers',
  'club_location_and_courses': 'Club location and courses',
  'nearby_courses_within_50_km': 'Nearby Courses (within 50 km)',
  'whatsapp_link': 'Whatsapp link',
  'we_chat_link': 'Wechat link',
  'facebook_group_link': 'Facebook group link',
  'club_description': 'Club description',
  'please_write_the_description_of_your_club': 'Please write the description of your club',
  'sorry_no_course_found_on_your_50_kilometer_radius':
      'Sorry! No course found on your 50 kilometer radius. That is why you can not create a club here',
  'sorry_your_club_is_within_10_km_of': 'Sorry! Your club is within 10 km of',
  'that_is_why_you_can_not_create_a_club_here': 'That is why you can not create a club here',
  'sending': 'Sending',
  'set_as_home': 'Set as Home',
  'your_location_is_turned_off': 'Your location is turned off',
  'pinned_location': 'Pinned Location',
  'speed': 'Speed',
  'glide': 'Glide',
  'turn': 'Turn',
  'fade': 'Fade',
  'price': 'Price',
  'edit_details': 'Edit Details',
  'update': 'Update',
  'sell_this_disc': 'Sell This Disc',
  'remove_from_wishlist': 'Remove From Wishlist',
  'mark_as_sold': 'Mark As Sold',
  'Please_write_your_sold_amount': 'Please write your sold amount',
  'update_disc_details': 'Update Disc Details',
  'brand': 'Brand',
  'model_name': 'Model name',
  'zone': 'Zone',
  'crave': 'Crave',
  'weight': 'Weight',
  'bag': 'Bag',
  'select_a_bag': 'Select a bag',
  'disc_image': 'Disc Image',
  'pick_color': 'Pick color',
  'upload_image': 'Upload image',
  'save_details': 'Save Details',
  'please_write_your_disc_speed': 'Please write your disc speed',
  'please_write_your_disc_glide': 'Please write your disc glide',
  'please_write_your_disc_turn': 'Please write your disc turn',
  'please_write_your_disc_fade': 'Please write your disc fade',
  'please_select_the_plastic_material_of_your_disc': 'Please select the plastic material of your disc',
  'please_write_your_disc_weight': 'Please write your disc weight',
  'please_select_a_bag_for_your_disc': 'Please select a bag for your disc',
  'mvp_trail': 'MVP Trail',
  'how_did_you_sell_the_disc': 'How did you sell the disc?',
  'tell_us_something_about_the_channel': 'Tell us something about the channel',
  'please_select_an_option': 'Please select an option',
  'please_write_something_about_your_channel': 'Please write something about your channel',
  'add_your_disc': 'Add your disc',
  'add_disc': 'Add Disc',
  'upload_a_photo': 'Upload a photo',
  'add_a_disc_to_wishlist': 'Add a disc to wishlist',
  'discs': 'Discs',
  'search_for_the_disc': 'Search for the disc',
  'use_the_search_field_and_search_for_the_disc_you_want_to_add': 'Use the search field and search for the disc you want to add',
  'search_by_discs_name': 'Search by discs name',
  'add_a_disc': 'Add a Disc',
  'browse_in_all_pdga_approved_discs': 'Browse in all PDGA approved discs',
  'be_nerdy_and_browse_in_all_discs': 'Be nerdy and browse in all discs',
  'open_browsing': 'Open Browsing',
  'ask_the_ai': 'Ask the AI',
  'answer_a_few_questions_and_ai_will_compare':
      'Answer a few questions and AI will compare your bag with thousands of bags and suggest a disc that can improve your game',
  'ai_disc_suggestion': 'AI disc suggestion',
  'how_long_do_you_throw': 'How long do you throw?',
  'pick_your_backhand_distance_that_you_reach': 'Pick your backhand distance that you reach',
  'select_distance': 'Select distance',
  'where_are_you_strongest': 'Where are you strongest?',
  'click_the_3_options_where_you_feel_you_are_strongest': 'Click the 3 options where you feel you are strongest',
  'stability_and_wind': 'Stability and wind',
  'click_1_option_where_you_feel_you_are_comfortable': 'Click 1 option where you feel you are comfortable',
  'how_comfortable_are_you_with_over_stable_discs': 'How comfortable are you with over stable discs?',
  'do_you_need_discs_that_perform_well_in_windy_conditions': 'Do you need discs that perform well in windy conditions?',
  'do_you_prefer_premium_plastics_or_base_plastic':
      'Do you prefer premium plastics ( more durable, glossy), or base plastic (grippy, softer)?',
  'plastic_grip_and_technicality': 'Plastic, grip and technicality',
  'click_on_1_option': 'Click on 1 options',
  'how_important_is_grip_in_wet_conditions_to_you?': 'How important is grip in wet conditions to you?',
  'do_you_play_in_heavily_wooded_courses': 'Do you play in heavily wooded courses or more open fields?',
  'create_sales_ad': 'Create sales ad',
  'sales_ad_notes': 'Sales ad Notes',
  'mandatory_to_upload_image_for_sales_ads': 'It is mandatory to upload image for sales ads',
  'speciality': 'Speciality',
  'please_write_the_price_of_your_disc': 'Please write the price of your disc',
  'please_add_your_disc_image': 'Please add your disc image',
  'added_discs': 'Added Discs',
  'created_sales_ad': 'Created sales ad',
  'add_another_disc': 'Add Another Disc',
  'create_another_sales_ad': 'Create Another Sales Ad',
  'your_disc_has_been_added_successfully': 'Your disc has been added successfully!',
  'we_have_created_this_sales_ad': 'We have created this\nsales ad!',
  'your_discs': 'Your discs',
  'wishlist': 'Wishlist',
  'see_flight_paths': 'See Flight Paths',
  'see_grid_paths': 'See Grid Paths',
  'pgda_approved_discs': 'PDGA approved discs',
  'browse_in_all_pgda_approved_discs': 'Browse in all PDGA approved discs',
  'recommended_disc': 'Recommended Disc',
  'add_disc_to_wishlist': 'Add Disc To Wishlist',
  'see_next': 'See Next',
  'reasons_why_this_discs_will_improve_your_game': 'Reasons why this discs will improve your game.',
  'your_club': 'Your club',
  'your_friends': 'Your friends',
  'search_discs': 'Search discs',
  'please_select_your_backhand_distance': 'Please select your backhand distance',
  'please_select_3_option': 'Please select 3 option',
  'please_select_1_option': 'Please select 1 option',
  'max_distance_drive': 'Max distance drive',
  'controlled_distance': 'Controlled Distance (Fairway Driver)',
  'straight_midrange': 'Straight Midrange',
  'over_stable_utility_midrange': 'Over stable utility Midrange',
  'understandable_turnover_midrange': 'Understandable Turnover Midrange',
  'approach_shots': 'Approach Shots (Short-range control)',
  'over_stable_approach': 'Over stable Approach(Flicks,Wind,Flex shots)',
  'putter_for_circle_1_puts': 'Putter for Circle 1 Puts',
  'putter_for_driving_circle_2_putts': 'Putter for Driving/Circle 2 Putts',
  'i_prefer_very_over_stable_discs': 'I prefer very over stable discs',
  'i_like_stable_straight_flyers': 'I like stable/straight flyers',
  'i_prefer_under_stable_discs': 'I prefer under stable discs (easier turnover/flex lines)',
  'i_like_a_mix_depending_on_the_situation': 'I like a mix depending on the situation',
  'yes': 'Yes',
  'no': 'No',
  'sometimes': 'Sometimes',
  'base_plastic': 'Base Plastic',
  'premium_plastic': 'Premium Plastic',
  'mix_no_preference': 'Mix/No Preference',
  'very_important': 'Very important',
  'somewhat_important': 'Somewhat important',
  'not_important': 'Not important',
  'wooded_courses': 'Wooded courses',
  'open_field': 'Open field',
  'both': 'Both',
  'your_friend': 'Your friend',
  'has_been_added': 'has been added!',
  'go_back': 'Go Back',
  'add_another_friend': 'Add Another Friend',
  'we_could_not_find_your_friend': 'Sorry! we could not find\nyour friend',
  'please_ask_your_friend_to_sign_up_in_capty': 'Please ask your friend to sign up in capty',
  'invite_again': 'Invite Again',
  'delete_friend': 'Delete Friend',
  'delete_friend_description': 'Are you sure you want to delete your friend? All your data with this friend will be lost forever!',
  'add_your_friend': 'Add your friend',
  'add_friend': 'Add Friend',
  'please_let_us_know_your_friend_pgda_number': 'Please let us know your friend PDGA number OR let us know their phone number',
  'your_friends_pdga_number': 'Your friends PDGA number',
  'or': 'Or',
  'your_friends_phone_number': 'Your friends Phone-number',
  'please_write_the_pgda_number_or_phone_number_of_your_friend': 'Please write the PGDA number or phone number of your friend',
  'please_select_the_country_of_your_friend': 'Please select the country of your friend',
  'friends': 'Friends',
  'card_mates': 'Cardmates',
  'deleted_successfully': 'Deleted Successfully',
  'clubs_you_can_join': 'Clubs you can join',
  'create_your_own_club': 'Create your Own Club',
  'search_for_your_club': 'Search for your club',
  'search_by_disc_name': 'search by disc name',
  'we_can_not_find_any_clubs_for_you_because_your_location_is_turned_off':
      'We can not find any clubs for you because your location is turned off.',
  'no_club_found_please_try_again': 'No Club Found. Please try again!',
  'club_events_close_to_you': 'Club events close to you',
  'open_event': 'Open Event',
  'hello': 'Hello',
  'leaderboards': 'Leaderboards',
  'open_club_view': 'Open club view',
  'open_leaderboards': 'Open LEADERBOARDS',
  'discs_in_bag': 'Discs in bag',
  'are_you_a_member_of_a_disc_golf_club': 'Are you a member of a disc golf club?',
  'no_club': 'No club',
  'choose_a_club': 'Choose a Club',
  'invite_club_members': 'Invite club members',
  'invite': 'Invite',
  'user_discs': 'User Discs',
  'more_from_this_seller': 'More from this seller',
  'disc_listings': 'Disc listings',
  'your_ads': 'Your ads',
  'marketplace': 'Marketplace',
  'share_sales_ad': 'Share Sales Ad',
  'create_n_sales_ad': 'Create\nsales add',
  'notifications': 'Notifications',
  'new': 'New',
  'previous': 'Previous',
  'no_notifications_available_now': 'No notifications available now. Please try again later.',
  'no_notification_found': 'No Notification Found!',
  'notification_preferences': 'Notification Preferences',
  'tournament_notifications': 'Tournament notifications',
  'club_notifications': 'Club notifications',
  'club_event_notifications': 'Club event notifications',
  'receive_a_reminder_at_least_1_day_before_your_tournament': 'Receive a reminder at lest 1 day before your tournament',
  'push_notification': 'Push Notification',
  'please_allow_notification_first': 'Please allow notification first',
  'edit_profile': 'Edit Profile',
  'are_you_a_left_handed_or_right_handed': 'Are you a left handed or right handed?',
  'undo_changes': 'Undo Changes',
  'update_profile': 'Update Profile',
  'please_select_an_option_of_your_hand': 'Please select an option of your hand',
  'view_my_tournament_bag': 'View My Tournament Bag',
  'select_language': 'Select Language',
  'receive_notifications_based_on_your_preferences': 'Receive notifications based on your preferences',
  'language': 'Language',
  'your_preferred_language_is': 'Your Preferred language is',
  'location': 'Location',
  'allow_location_access': 'Allow Location access',
  'your_currency': 'Your Currency',
  'select_currency': 'Select currency',
  'measurement': 'Measurement',
  'select_measurement': 'Select Measurement',
  'your_date_and_time': 'Your Date&Time',
  '24_hour_time': '24-Hour Time',
  'set_automatically': 'Set automatically',
  'time_zone': 'Time Zone',
  'post_your_feedback': 'Post your feedback',
  'post_feedback': 'Post Feedback',
  'write_your_feedback_here': 'Write your feedback here',
  'please_write_your_feedback': 'Please write your feedback',
  'suggest_feature': 'Suggest feature',
  'feature_title': 'Feature title',
  'i_want_a_match_service': 'I want a match service',
  'feedback_type': 'Feedback type',
  'write_your_suggestion_here': 'Write your suggestion here',
  'select_feedback_type': 'Select feedback type',
  'send_suggestion': 'Send Suggestion',
  'suggested_features': 'Suggested features',
  'please_write_your_feature_title': 'Please write your feature title',
  'please_write_your_feature_suggestion': 'Please write your feature suggestion',
  'suggestion_details': 'Suggestion Details',
  'suggested_feature': 'Suggested feature',
  'suggestion_sent_successfully': 'Suggestion send successfully',
  'congratulations': 'Congratulations',
  'attention': 'Attention',
  'message': 'Message',
  'error': 'Error',
  'home': 'Home',
  'create_a_disc_newline_sales_ad': 'Create a disc\nsales ad',
  'add_a_friend': 'Add a friend',
  'add_a_disc_newline_to_your_bag': 'Add a disc\nto your bag',
  'delete': 'Delete',
  'left': 'Left',
  'right': 'Right',
  'new_disc_never_thrown_and_no_name_inside': 'New disc - (Never thrown and no name inside)',
  'used_disc': 'Used disc',
  'died_disc': 'Died disc',
  'collector_item': 'Collector item',
  'a_verification_code_sent_to_your_phone_number': 'A verification code sent to your phone number',
  'invalid_verification_code': 'Invalid verification code',
  'the_udisc_username_has_already_exists': 'The udisc username has already exists',
  'the_pdga_number_has_already_exists': 'The pdga number has already exists',
  'conversations_deleted_successfully': 'Conversations Deleted Successfully',
  'club_created_successfully': 'Club created successfully',
  'joined_successfully': 'Joined successfully',
  'you_left_the_club': 'You left the club',
  'event_created_successfully': 'Event created successfully',
  'end_time_should_be_after_start_time': 'End time should be after start time',
  'duration_must_be_at_least_30_minutes': 'Duration must be at least 30 minutes.',
  'please_select_the_day_after': 'Please select the day after',
  'select_date': 'Select date',
  'no_disc_found': 'No Disc Found!',
  'you_have_no_disc_available_now_please_add_your_disc': 'You have no disc available now! Please add your disc.',
  'no_result_found': 'No Result Found!',
  'no_search_records_found_please_adjust_your_search_criteria':
      'No search records found. Please adjust your search criteria or try again with different keywords for better results.',
  'sorry_tab_view_not_supported_yet': 'Sorry! Tab View Not Supported Yet!',
  'we_will_soon_bring_the_tab_view_for_you': 'We will soon bring the tab view for you.',
  'no_items_found': 'No items found',
  'characters': 'characters',
  'password_strength': 'Password strength',
  'no_pdga_description':
      'Sorry, you are currently not signed up for any PDGA tournament Once we register that you are going to a tournament, we will shows sales ads here from players going to the same tournament',
  'sorry_we_cant_show_you_the_nearest_sales_ads_to_your_location':
      'Sorry, we cant show you the nearest sales ads to your location as you are not sharing your location with us',
  'adjust_club_details': 'Adjust club details',
  'edit_club_courses': 'Edit club courses',
  'control_other_relevant_club_data': 'Control other relevant club data',
  'intersection': 'Intersection',
  'discs_for_sale': 'Discs for sale',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'added_waitlist_description': 'You have been signed up for waitlist. We will contact when you open up in your country.',
  'thank_you': 'Thank You',
  'continue': 'continue',
  'which_country_are_you_from': 'Which country you are from?',
  'your_email': 'Your email',
  'your_name': 'Your name',
  'please_join_our_waitlist': 'Please join our waitlist',
  'submit': 'Submit',
  'please_select_your_country': 'Please select your country',
  'continue_with_google': 'Continue with Google',
  'continue_with_aApple': 'Continue with Apple',
  'please_sign_out_from_icloud': 'You are previously signed in. Please sign out from iCloud',
  'your_basic_information_helps_us_to_create_a_better_profile_for_you':
      'Your basic information helps us to create a better profile for you',
  'almost_there': 'Almost there',
  'your_profile_image': 'Your Profile Image',
  'take_photo': 'Take Photo',
  'upload_photo': 'Upload Photo',
  'your_phone_number': 'Your phone number',
  'save_and_continue': 'Save & Continue',
  'report_title': 'Report Title',
  'report_description': 'Report Description',
  'write_your_description_here': 'Write your description here',
  'send_report': 'Send Report',
  'please_write_the_title_of_report': 'Please write the title of report',
  'please_write_the_description_of_report': 'Please write the description of report',
  'report_sent_successfully': 'Report sent successfully',
  'you_cannot_vote_on_your_own_feature': 'You cannot vote on your own feature.',
  'vote_successful': 'Vote successful',
  'phone_number_must_be_at_least': 'Phone number must be at least',
  'name': 'Name',
  'email': 'Email',
  'we_already_have_your_request': 'We already have your request. Please try again with another email.',
  'bag_created_successfully': 'Bag created successfully',
  'plus_new_bag': '+ New Bag',
  'add_bag': 'Add Bag',
  'update_bag': 'Update bag',
  'tournament': 'Tournament',
  'description': 'Description',
  'write_description_here': 'Write description here',
  'please_write_your_bag_name': 'Please write your bag name',
  'please_write_your_bag_description': 'Please write your bag description',
  'search_for_the_disc_you_want_to_add_to_your_bag': 'Search for the disc you want to add to your bag',
  'disc_created_successfully': 'Disc created successfully',
  'disc_update_successfully': 'Disc updated successfully',
  'disc_deleted_successfully': 'Disc deleted successfully',
  'removed_successfully_from_wishlist': 'Removed successfully from wishlist',
  'search_disc': 'Search Disc',
  'currency_updated_successfully': 'Currency updated successfully',
  'sales_ad_disc_created_successfully': 'Sales ad disc created successfully',
  'price_updated_successfully': 'Price updated successfully',
  'sold_information_updated_successfully': 'Sold information updated successfully',
  'gram': 'gram',
  'sales_ad_type': 'Sales Ad Type',
  'addresses': 'Addresses',
  'add_new_address': 'Add New Address',
  'delete_address': 'Delete Address',
  'are_you_sure_you_want_to_delete_this_address': 'Are you sure you want to remove this address?',
  'created_successfully': 'Created successfully',
  'updated_successfully': 'Updated successfully',
  'search': 'Search',
  'pdga_disc': 'Pdga Disc',
  'if_your_disc_is_not_available_in_the_list_please_submit':
      'If your disc is not available in the list, please submit a request and we will help locate it promptly.',
  'request_a_disc': 'Request a Disc',
  'yes_please': 'Yes, Please',
  'are_you_sure_you_want_to_close_the_application': 'Are you sure, you want to close the application?',
  'send_request': 'Send Request',
  'write_the_name_of_your_disc': 'Write the name of your disc',
  'please_write_the_name_of_your_disc': 'Please write the name of your disc',
  'write_the_brand_name_of_your_disc': 'Write the brand name of your disc',
  'please_write_the_brand_name_of_your_disc': 'Please write the brand name of your disc',
  'write_the_web_link_of_your_disc': 'Write the web link of your disc',
  'please_write_the_web_link_of_your_disc': 'Please write the web link of your disc',
  'please_add_a_valid_link': 'Please add a valid link',
  'please_upload_your_disc_image': 'Please upload your disc image',
  'request_sent_successfully': 'Request sent successfully',
  'we_will_review_the_data_from_this_discs':
      'We will review the data from this discs. And will add it to the main disc list so that you can add it to your bag.',
  'close': 'Close',
  'onboarding_1':
      "Take your disc golf game to the next level. Whether you're aiming for a personal best, climbing your club's leaderboard, or competing at PDGA events, Capty helps you track your progress, refine your skills, and challenge friends.",
  'onboarding_2':
      'Who in the club has played the best last 10 rounds? Who is the best Circle 1 putter? Who has the best PDGA improvement in the last year? - Get the answers in Capty',
  'onboarding_3':
      "Disc golf is more than just a sport—it's a community. Capty connects you when you travel, find local events, and even spot who's playing at the same tournaments. Buy and sell discs directly within your local scene.",
  'address': 'Address',
  'please_add_your_address': 'Please add your address',
  'profile_picture_uploaded_successfully': 'Profile picture uploaded successfully',
  'request_rejected': 'Request rejected',
  'no_friend_found': 'No Friend Found',
  'already_added_as_friend': 'Already added as friend',
  'you_already_sent_a_friend_request_with_this_person': 'You already sent a friend request with this person',
  'send_a_friend_request_to_your_friend': 'Send a friend request to your friend',
  'accept_request': 'Accept Request',
  'are_you_sure_you_want_to_add_this_person_as_a_friend': 'Are you sure you want to add this person as a friend?',
  'no_request_found': 'No Request Found',
  'no_requests_are_available_in_your_list_please_add_your_friend': 'No requests are available in your list. Please add your friend.',
  'cancel_request': 'Cancel Request',
  'requests': 'Requests',
  'request_cancelled': 'Request cancelled',
  'reject_request': 'Reject Request',
  'all': 'All',
  'leaderboard': 'Leaderboard',
  'go_to_disc_management': 'Go To Disc Management',
  'please_pick_a_color_of_your_disc_image_or_add_your_disc_image': 'Please pick a color of your disc image or add your disc image',
  'no_player_found': 'No player found!!',
  'its_more_fun_to_play_with_club_member_or_friends':
      "It's more fun to play with your club members or friends. Invite your club members or friends to give and share kudos.",
  'disc_management': 'Disc Management',
  'hand_expert': 'Hand Expert',
  'no_address_found': 'No Address Found',
  'no_address_available_now_please_add_your_address_and_try_again': 'No address available now. Please add your address and try again.',
  'no_sales_ad_disc_found': 'No sales ad disc found',
  'add_sales_ad_disc': 'Add sales ad disc',
  'you_have_no_disc_available_now_please_add_your_sales_ad_disc': 'You have no disc available now! Please add your sales ad disc.',
  'no_wishlist_disc_found': 'No wishlist disc found',
  'you_have_no_disc_available_now_please_add_your_wishlist_disc': 'You have no disc available now! Please add your wishlist disc.',
  'add_wishlist_disc': 'Add Wishlist Disc',
  'total_club': 'Total Club',
  'the_app_is_more_fun_when_your_friends_are_here': 'The app is more fun when your friends are here',
  'invite_your_friends': 'Invite Your Friends',
  'just_signed_up_in_capty': 'Just signed up in Capty',
  'and_joined_the_club': 'and joined the club',
  'and_compare_pdga_rank_and_buy_sell_disc': 'and compare PDGA rank and buy/sell disc',
  'capty_a_disc_golf_marketplace': 'Capty-A Disc Golf Marketplace',
  'you_can_not_move_disc_on_this_bag': 'You can not move disc on this bag',
  'disc_added_in': 'Disc added in',
  'this_disc': 'This disc',
  'already_in': 'already in',
  'this_bag': 'this bag',
  'copy_this_link_to_share': 'Copy this link to share',
  'share_your_sales_ad_page': 'Share your Sales ad page',
  'share_sales_ad_desc':
      'We have made a page that shows all the discs you have for sale right now.\nPlease share it in your club or in the facebook Buy/sell group.',
  'copied': 'copied',
  'read_more': 'Read More',
  'show_less': 'Show Less',
  'about_the_disc': 'About this Disc',
  'please_select_a_home_course': 'Please select a home course',
  'you_have_not_added_any_friends_yet_add_your_first_friend_now': 'You have not added any friends yet. Add your first friend now.',
  'tournament_discs': 'Tournament Discs',
  'you_have_no_disc_in_your_tournament_bag_please_add_your_disc': 'You have no disc in your tournament bag. Please add your disc.',
  'you_have_joined': 'You have joined',
  'the_club_is_more_fun_when_your_club_members_are_here': 'The app is more fun when your club members are here',
  'your_clubs': 'Your clubs',
  'join_a_new_club': 'Join a new club',
  'default_club': 'Default Club',
  'leave_club': 'Leave Club',
  'set_as_default': 'Set As Default',
  'default_club_updated_successfully': 'Default club updated successfully',
  'no_messages_available_now': 'No messages available now. Please check back later.',
  'no_message_found': 'No Message Found!',
  'email_already_exist_please_try_with_a_new_email': 'Email already exists. Please try with a new email.',
  'disc_updated_successfully': 'Disc updated successfully',
  'this_email_already_exist_please_try_with_another_email': 'This email already exists! Please try with another email',
  'this_phone_number_already_exist_please_try_with_another_phone_number':
      'This phone number already exists! Please try with another phone number',
  'deleting_account': 'Deleting Account',
  'server_error_please_contact_with_capty': 'Server error!! Please contact with CAPTY.',
  'remove_sales_ad': 'Remove Sales Ad',
  'place_information_not_found': 'Place information not found',
  'extremely_used_hardly_recognizable': 'Extremely used, hardly recognizable.',
  'extremely_used': 'Extremely used',
  'very_used': 'Very used',
  'used_a_lot_fully_covered_in_marks_cuts_or_scratches_very_altered_flight_compared_to_new':
      'Used a lot, fully covered in marks, cuts or scratches, very altered flight compared to new.',
  'used_a_lot_of_marks_cuts_or_scratches_altered_flight_compared_to_new':
      'Used, a lot of marks, cuts or scratches, altered flight compared to new.',
  'used_normal_marks_cuts_or_scratches_slightly_altered_flight_compared_to_new':
      'Used, normal marks, cuts or scratches, slightly altered flight compared to new.',
  'lightly_used_with_a_few_marks_cuts_or_scratches_flies_as_new': 'Lightly used, with a few marks, cuts or scratches, flies as new.',
  'lightly_used_no_significant_marks_cuts_or_scratches_flies_as_new':
      'Lightly used, but no significant marks, cuts or scratches, flies as new.',
  'as_good_as_new_tested_a_couple_of_times_has_name_and_number_inside':
      'As good as new, tested a couple of times - has name and number inside.',
  'no_marks_cuts_or_scratches_no_name_inside': 'No marks, cuts or scratches and no name inside.',
  'countries': 'Countries',
  'users': 'Users',
  'sales_ads_from_your_countries': 'Sales ads from your countries',
  'select_your_country_to_see_sales_ads': 'Select your country to see sales ads from your country',
  'select_country': 'Select country',
  'view_sales_ads': 'View Sales Ads',
  'login_to_continue': 'Login to continue',
  'create_your_own_account_to_explore_more': 'Create  your own account to explore more',
  'create_account': 'Create Account',
  'login': 'Login',
  'disc_weight': 'Disc Weight',
  'disc_condition': 'Disc Condition',
  'disc_special_features': 'Disc special features',
  'disc_description': 'Disc Description',
  'pdga_rating_desc':
      'This leaderboard sorts your clubmember/friends based on your PDGA rating. The person with the best rating is in the top',
  'best_pdga_improvement_desc':
      'This leaderboard is under construction! But it will list your clubmembers/friends with the best PDGA improvement in the last 365 days',
  'best_pdga_improvement': 'Best PDGA Improvement',
  'messages': 'Messages',
  'filter_in_marketplace': 'Filter in Marketplace',
  'no_pdga_discs_are_available_now_please_try_again_later': 'No pdga discs are availabe now. Please try again later.',
  'filter_marketplace_discs': 'Filter Marketplace Discs',
  'filter': 'Filter',
  'type': 'Type',
  'online_now': 'Online Now',
  'offline_now': 'Offline Now',
  'under_development': 'Under Development',
  'flight_paths': 'Flight Paths',
  'tags': 'Tags',
  'view': 'View',
  'tournament_bag': 'Tournament Bag',
  'extra_s': "'s",
  'seller_disc_details': 'Seller Disc Details',
  'my_disc_details': 'My Disc Details',
  'select_brands': 'Select Brands',
  'search_by_brand_name': 'Search by brand name',
  'please_select_any_brand': 'Please select any brand',
  'we_could_not_find_any_brands_right_now_please_try_again_later': 'We couldn’t find any brands right now. Please try again later.',
  'no_brand_found': 'Np Brand Found',
  'sales_add_from_club_members': 'Sales add from club members',
  'here_we_will_show_you_the_sales_ad_from_the_members_of_your_default_club':
      'Here we will show you the sales ad from the members of your default club',
  'in_this_view_we_are_showing_you_all_sales_ads_from_users_who_are_going_to_this_tournament':
      'In this view, we are showing you all sales ads from users who are going to this tournament.',
  'your_tournaments': 'Your Tournaments',
  'please_select_at_least_one_filter_option': 'Please select at least one filter option',
  'from': 'From',
  'to': 'to',
  'speed_1_15': 'Speed (1-15)',
  'glide_0_7': 'Glide (0 -7)',
  'turn_5_1': 'Turn (-5 - 1)',
  'fade_0_5': 'Fade (0- 5)',
  'today': 'today',
  'yesterday': 'Yesterday',
  'flight_numbers': 'Flight Numbers',
  'open_message': 'open Message',
  'specialty': 'Specialty',
  'no_speciality_available': 'No Speciality Available',
  'about_this_disc': 'About this Disc',
  'reset_filter': 'Reset Filter',
  'update_available': 'Update Available',
  'a_new_version_of_the_app_is_available_please_update_to_continue': 'A new version of the app is available. Please update to continue.',
  'update_now': 'Update Now',
  'unable_to_update_now_please_try_again_later': 'Unable to update now. Please try again later.',
  '2nd_player': '2nd Player',
  '1st_player': '1st Player',
  '3rd_player': '3rd Player',
  'share_the_app_with_other_members_of': 'Share the app with other members of',
  'to_see_more_people_on_this_leaderboard': 'to see more people on this leaderboard.',
  'share_capty': 'Share Capty',
  'go_to_marketplace': 'Go To Marketplace',
  'club_point': 'Club Point',
  'invite_your_friend': 'Invite Your Friend',
  'share_the_app_with_your_friends': 'Share the app with your friends',
  'capty_disc_golf_app': 'Capty Disc Golf App',
  'has_joined_the_app_capty': 'has joined the app Capty',
  'please_follow_this_link_so_that_you_can_compare_ratings_and_buy_sell_and_swap_discs_among_eachother':
      'Please follow this link so that you can compare ratings and buy, sell and swap discs among eachother',
  'no_internet_connection_please_check_your_network': 'No internet connection. Please check your network.',
  'request_timed_out_please_check_your_internet_connection': 'Request timed out. Please check your internet connection.',
  'is_a_same_member_of': 'is a same member of',
  'is_a_friend_of_you': 'is a friend of you',
  'is_not_a_friend_of_you': 'is not a friend of you',
  'no_wait': 'No, Wait',
  'change_language': 'Change Language',
  'do_you_want_to_change_the_language_to': 'Do you want to change the language to',
  'based_on_your_selected_country': 'based on your selected country',
  'your_language': 'Your language',
  'you_already_vote_on_this_feature': 'You already vote on this feature.',
  'search_by_club_name': 'Search by club name',
  'bag_deleted_successfully': 'Bag deleted successfully',
  'you_already_have_a_bag_with_this_name': 'You already have a bag with this name.',
  'are_you_sure_you_want_to_delete_the_bag': 'Are you sure you want to delete the bag',
  'you_must_write_your_full_name': 'You must write your full name',
  'message_not_found': 'Message not found',
  'we_are_in_beta_mode': 'We are in BETA mode!',
  'you_have_installed_the_first_version_of_the_app_thank_you_for_your_help_testing':
      'You have installed the first version of the app. Thank you for your help testing!',
  'we_expect_to_switch_from_beta_mode_to_normal_user_mode_between_august_and_september_2025':
      'We expect to switch from beta mode to normal user mode between august and September 2025.',
  'please_do_not_add_all_your_discs_at_this_point_but_send_us_as_much_feedback_as_possible':
      'Please do not add all your discs at this point, but send us as much feedback as possible. Please do not share the app yet!',
  'okay_i_understand': 'Okay, I Understand!',
  'the_capty_app_is_live': 'The CAPTY app is live!',
  'you_have_installed_the_first_version_of_the_app': 'You have installed the first version of the app.',
  'the_dream_is_to_create_an_app_that_some_day_in_future':
      'The dream is to create an app, that SOME DAY IN THE FUTURE will be the epicenter of your disc golf life.',
  'but_to_make_the_app_better_we_need_your_inputs':
      'But to make the app better, we need your inputs! Please send us feedback on bugs and your improvement ideas here',
  'go_to_feedback_page': 'Go To Feedback page',
  'pdga_number_already_used_please_try_your_unique_pdga_number': 'Pdga number already used. Please try your unique pdga number.',
  'shipping': 'Shipping',
  'i_want_to_offer_shipping': 'I want to offer shipping',
  'these_are_places_where_your_paths_cross': 'These are places where your paths cross',
  'you_are_both_members_of_these_clubs': 'You are both members of these clubs',
  'you_will_both_attend': 'You will both attend',
  'the_seller_pick_up_points': 'The seller pick up points',
  'this_seller_offers_shipping': 'This seller offers shipping.',
  'this_seller_does_not_offers_shipping': 'This seller does not offers shipping.',
  'rotate_disc_image': 'Rotate Disc Image',
  'add_your_home_address': 'Add your home address',
  'home_address': 'Home address',
  'pickup_points': 'Pickup points',
  'add_your_pickup_points': 'Add your pickup points',
  'add_another_pickup_point': 'Add another pickup point',
  'okay_understood': 'Okay, Understood',
  'address_information_not_found': 'Address information not found',
  'address_coordinates_not_found': 'Address coordinates not found',
  'city_not_found': 'City not found',
  'state_not_found': 'State not found',
  'postal_code_not_found': 'Postal code not found',
  'do_you_want_to_offer_shipping': 'Do you want to offer shipping?',
  'if_you_turn_this_option_on_you_are_telling_the_buyers_that_if_they_pay_you':
      'If you turn this option on, you are telling the buyers that if they pay you for the shipping, you will manage shipping the disc to them',
  'add_home_address': 'Add Home Address',
  'before_you_can_create_your_first_sales_ad_please_add_your_shipping_address':
      'Before you can create your first sales ad, please add your shipping address.',
  'go_to_seller_settings': 'Go To Seller Settings',
  'from_club_member': 'From club member',
  'tournaments': 'Tournaments',
  'tournament_bag_menu': 'Tournament Bag',
  'backup_bag': 'Backup Bag',
  'please_select_any_tag': 'Please select any tag',
  'we_could_not_find_any_tags_right_now_please_try_again_later': 'We could not find any tags right now. Please try again later.',
  'no_tag_found': 'No Tag Found',
  'seller_settings': 'Seller Settings',
  'please_select_your_home_address': 'Please select your home address.',
  'select_tags': 'Select Tags',
  'search_by_tag_name': 'Search by tag name',
  'if_you_tag_your_sales_ad_it_makes_it_more': 'If you tag your sales ad, it makes it more visible to buyers',
  'country': 'Country',
  'sort_by': 'Sort By',
  'newest': 'Newest',
  'popularity': 'Popularity',
  'please_give_us_some_info_about_the_discs': 'Please give us some info about the discs',
  'online_link_of_the_disc': 'Online link of the disc',
  'image_of_the_disc': 'Image of the disc',
  'founder': 'Founder',
  'join_waitlist': 'Join Waitlist',
  'view_image': 'View Image',
  'please_write_any_disc_name': 'Please write any disc name',
  'write_here': 'Write here',
  'send_message': 'Send Message',
  'could_not_open_url': 'Could not open url',
  // New translations
  'club_members': 'Club Members',
  'search_by_name': 'Search by name',
  'no_club_member_found': 'No club member found',
  'club_member_not_found_please_recheck_entered_information': 'Club member not found. Please recheck entered information',
  'view_profile': 'View Profile',
  'search_result_for': 'Search result for',
  'clear_search': 'Clear Search',
  'favourites': 'Favourites',
  'please_select_any_disc_plastic': 'Please select any disc plastic',
  'no_disc_plastic_found': 'No disc plastic found',
  'search_by_plastic_name': 'Search by plastic name',
  'we_could_not_find_any_plastic_right_now_please_try_again_later': 'We could not find any plastic right now. Please try again later.',
  'no_favourite_disc_found': 'No Favourite Disc Found!',
  'show_more': 'Show More',
  'you_have_no_sales_ad_disc_in_marketplace_please_create_your_sales_ads':
      'You have no sales ad disc in marketplace. Please create your sales ads.',
  'has_no_available_disc_in_marketplace_please_check_back_later': 'has no available disc in marketplace. Please check back later.',
  'this_player': 'This player',
  'no_sales_ad_found': 'No Sales Ads Found!',
  'no_tournament_discs_found': 'No Tournament Discs Found!',
  'has_no_disc_in_the_tournament_bag': 'has no disc in the tournament bag',
  'click_here_if_you_want_to_join_the_admin_team_for_the_club': 'Click on below button if you want to join the admin team for the club',
  'join_as_administrator': 'Join As Administrator',
  'join_administrator': 'Join Administrator',
  'are_you_sure_you_want_to_join_as_an_administrator': 'Are you sure you want to join as an administrator?',
  'connected_courses': 'Connected courses',
  'connect_new_course': 'Connect New Course',
  'club_links': 'Club links',
  'whats_app_link': 'WhatsApp link',
  'no_link_available_yet': 'No link available yet.',
  'no_description_available_now': 'No description available now.',
  'my': 'My',
  'stability': 'Stability',
  'select_special_features': 'Select special features',
  'feature_selected': 'feature selected',
  'update_disc': 'Update Disc',
  'save_details_and_add_to_wishlist': 'Save Details & Add To Wishlist',
  'capty_id': 'Capty Id',
  '': ''
};

/*I will give you sentences you have to convert that
like the sentence Cancelled note
converted output will be cancelled_note*/
