import 'package:app/extensions/string_ext.dart';
import 'package:app/preferences/app_preferences.dart';

class DefaultCountry {
  int id;
  String code;
  String image;
  String name;

  DefaultCountry({this.id = -1, this.code = '', this.image = '', this.name = ''});

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['code'] = code;
    map['image'] = image;
    map['name'] = name;
    return map;
  }

  static List<DefaultCountry> countries_by_name(String key) {
    var searchKey = key.toKey;
    var dbCodes = AppPreferences.countries.isEmpty ? [] : AppPreferences.countries.map((item) => item.code.toKey).toList();
    var updatedCountries = dbCodes.isEmpty ? COUNTRY_LIST : COUNTRY_LIST.where((item) => !dbCodes.contains(item.code.toKey)).toList();
    if (searchKey.isEmpty || updatedCountries.isEmpty) return updatedCountries;
    return updatedCountries.where((item) => item.name.toKey.startsWith(searchKey.toKey)).toList();
  }
}

final List<DefaultCountry> COUNTRY_LIST = [
  DefaultCountry(id: 0, code: 'af', image: 'assets/flags/af.png', name: 'Afghanistan'),
  DefaultCountry(id: 1, code: 'al', image: 'assets/flags/al.png', name: 'Albania'),
  DefaultCountry(id: 2, code: 'dz', image: 'assets/flags/dz.png', name: 'Algeria'),
  DefaultCountry(id: 3, code: 'dz', image: 'assets/flags/dz.png', name: 'Andorra'),
  DefaultCountry(id: 4, code: 'ao', image: 'assets/flags/ao.png', name: 'Angola'),
  DefaultCountry(id: 5, code: 'ag', image: 'assets/flags/ag.png', name: 'Antigua and Barbuda'),
  DefaultCountry(id: 6, code: 'ar', image: 'assets/flags/ar.png', name: 'Argentina'),
  DefaultCountry(id: 7, code: 'am', image: 'assets/flags/am.png', name: 'Armenia'),
  DefaultCountry(id: 8, code: 'au', image: 'assets/flags/au.png', name: 'Australia'),
  DefaultCountry(id: 9, code: 'at', image: 'assets/flags/at.png', name: 'Austria'),
  DefaultCountry(id: 10, code: 'az', image: 'assets/flags/az.png', name: 'Azerbaijan'),
  DefaultCountry(id: 11, code: 'bs', image: 'assets/flags/bs.png', name: 'Bahamas'),
  DefaultCountry(id: 12, code: 'bh', image: 'assets/flags/bh.png', name: 'Bahrain'),
  DefaultCountry(id: 13, code: 'bd', image: 'assets/flags/bd.png', name: 'Bangladesh'),
  DefaultCountry(id: 14, code: 'bb', image: 'assets/flags/bb.png', name: 'Barbados'),
  DefaultCountry(id: 15, code: 'by', image: 'assets/flags/by.png', name: 'Belarus'),
  DefaultCountry(id: 16, code: 'be', image: 'assets/flags/be.png', name: 'Belgium'),
  DefaultCountry(id: 17, code: 'bz', image: 'assets/flags/bz.png', name: 'Belize'),
  DefaultCountry(id: 18, code: 'bj', image: 'assets/flags/bj.png', name: 'Benin'),
  DefaultCountry(id: 19, code: 'bt', image: 'assets/flags/bt.png', name: 'Bhutan'),
  DefaultCountry(id: 20, code: 'bo', image: 'assets/flags/bo.png', name: 'Bolivia (Plurinational State of)'),
  DefaultCountry(id: 21, code: 'ba', image: 'assets/flags/ba.png', name: 'Bosnia and Herzegovina'),
  DefaultCountry(id: 22, code: 'bw', image: 'assets/flags/bw.png', name: 'Botswana'),
  DefaultCountry(id: 23, code: 'br', image: 'assets/flags/br.png', name: 'Brazil'),
  DefaultCountry(id: 24, code: 'bn', image: 'assets/flags/bn.png', name: 'Brunei Darussalam'),
  DefaultCountry(id: 25, code: 'bg', image: 'assets/flags/bg.png', name: 'Bulgaria'),
  DefaultCountry(id: 26, code: 'bf', image: 'assets/flags/bf.png', name: 'Burkina Faso'),
  DefaultCountry(id: 27, code: 'bi', image: 'assets/flags/bi.png', name: 'Burundi'),
  DefaultCountry(id: 28, code: 'cv', image: 'assets/flags/cv.png', name: 'Cabo Verde'),
  DefaultCountry(id: 29, code: 'kh', image: 'assets/flags/kh.png', name: 'Cambodia'),
  DefaultCountry(id: 30, code: 'cm', image: 'assets/flags/cm.png', name: 'Cameroon'),
  DefaultCountry(id: 31, code: 'ca', image: 'assets/flags/ca.png', name: 'Canada'),
  DefaultCountry(id: 32, code: 'cf', image: 'assets/flags/cf.png', name: 'Central African Republic'),
  DefaultCountry(id: 33, code: 'td', image: 'assets/flags/td.png', name: 'Chad'),
  DefaultCountry(id: 34, code: 'cl', image: 'assets/flags/cl.png', name: 'Chile'),
  DefaultCountry(id: 35, code: 'cn', image: 'assets/flags/cn.png', name: 'China'),
  DefaultCountry(id: 36, code: 'co', image: 'assets/flags/co.png', name: 'Colombia'),
  DefaultCountry(id: 37, code: 'km', image: 'assets/flags/km.png', name: 'Comoros'),
  DefaultCountry(id: 38, code: 'cg', image: 'assets/flags/cg.png', name: 'Congo'),
  DefaultCountry(id: 39, code: 'cd', image: 'assets/flags/cd.png', name: 'Congo, Democratic Republic of the'),
  DefaultCountry(id: 40, code: 'cr', image: 'assets/flags/cr.png', name: 'Costa Rica'),
  DefaultCountry(id: 41, code: 'ci', image: 'assets/flags/ci.png', name: "Côte d'Ivoire"),
  DefaultCountry(id: 42, code: 'hr', image: 'assets/flags/hr.png', name: 'Croatia'),
  DefaultCountry(id: 43, code: 'cu', image: 'assets/flags/cu.png', name: 'Cuba'),
  DefaultCountry(id: 44, code: 'cy', image: 'assets/flags/cy.png', name: 'Cyprus'),
  DefaultCountry(id: 45, code: 'cz', image: 'assets/flags/cz.png', name: 'Czechia'),
  DefaultCountry(id: 46, code: 'dk', image: 'assets/flags/dk.png', name: 'Denmark'),
  DefaultCountry(id: 47, code: 'dj', image: 'assets/flags/dj.png', name: 'Djibouti'),
  DefaultCountry(id: 48, code: 'dm', image: 'assets/flags/dm.png', name: 'Dominica'),
  DefaultCountry(id: 49, code: 'do', image: 'assets/flags/do.png', name: 'Dominican Republic'),
  DefaultCountry(id: 50, code: 'ec', image: 'assets/flags/ec.png', name: 'Ecuador'),
  DefaultCountry(id: 51, code: 'eg', image: 'assets/flags/eg.png', name: 'Egypt'),
  DefaultCountry(id: 52, code: 'sv', image: 'assets/flags/sv.png', name: 'El Salvador'),
  DefaultCountry(id: 53, code: 'gq', image: 'assets/flags/gq.png', name: 'Equatorial Guinea'),
  DefaultCountry(id: 54, code: 'er', image: 'assets/flags/er.png', name: 'Eritrea'),
  DefaultCountry(id: 55, code: 'ee', image: 'assets/flags/ee.png', name: 'Estonia'),
  DefaultCountry(id: 56, code: 'sz', image: 'assets/flags/sz.png', name: 'Eswatini'),
  DefaultCountry(id: 57, code: 'et', image: 'assets/flags/et.png', name: 'Ethiopia'),
  DefaultCountry(id: 58, code: 'fj', image: 'assets/flags/fj.png', name: 'Fiji'),
  DefaultCountry(id: 59, code: 'fi', image: 'assets/flags/fi.png', name: 'Finland'),
  DefaultCountry(id: 60, code: 'fr', image: 'assets/flags/fr.png', name: 'France'),
  DefaultCountry(id: 61, code: 'ga', image: 'assets/flags/ga.png', name: 'Gabon'),
  DefaultCountry(id: 62, code: 'gm', image: 'assets/flags/gm.png', name: 'Gambia'),
  DefaultCountry(id: 63, code: 'ge', image: 'assets/flags/ge.png', name: 'Georgia'),
  DefaultCountry(id: 64, code: 'de', image: 'assets/flags/de.png', name: 'Germany'),
  DefaultCountry(id: 65, code: 'gh', image: 'assets/flags/gh.png', name: 'Ghana'),
  DefaultCountry(id: 66, code: 'gr', image: 'assets/flags/gr.png', name: 'Greece'),
  DefaultCountry(id: 67, code: 'gd', image: 'assets/flags/gd.png', name: 'Grenada'),
  DefaultCountry(id: 68, code: 'gt', image: 'assets/flags/gt.png', name: 'Guatemala'),
  DefaultCountry(id: 69, code: 'gn', image: 'assets/flags/gn.png', name: 'Guinea'),
  DefaultCountry(id: 70, code: 'gw', image: 'assets/flags/gw.png', name: 'Guinea-Bissau'),
  DefaultCountry(id: 71, code: 'gy', image: 'assets/flags/gy.png', name: 'Guyana'),
  DefaultCountry(id: 72, code: 'ht', image: 'assets/flags/ht.png', name: 'Haiti'),
  DefaultCountry(id: 73, code: 'hn', image: 'assets/flags/hn.png', name: 'Honduras'),
  DefaultCountry(id: 74, code: 'hu', image: 'assets/flags/hu.png', name: 'Hungary'),
  DefaultCountry(id: 75, code: 'is', image: 'assets/flags/is.png', name: 'Iceland'),
  DefaultCountry(id: 76, code: 'in', image: 'assets/flags/in.png', name: 'India'),
  DefaultCountry(id: 77, code: 'id', image: 'assets/flags/id.png', name: 'Indonesia'),
  DefaultCountry(id: 78, code: 'ir', image: 'assets/flags/ir.png', name: 'Iran (Islamic Republic of)'),
  DefaultCountry(id: 79, code: 'iq', image: 'assets/flags/iq.png', name: 'Iraq'),
  DefaultCountry(id: 80, code: 'ie', image: 'assets/flags/ie.png', name: 'Ireland'),
  DefaultCountry(id: 81, code: 'il', image: 'assets/flags/il.png', name: 'Israel'),
  DefaultCountry(id: 82, code: 'it', image: 'assets/flags/it.png', name: 'Italy'),
  DefaultCountry(id: 83, code: 'jm', image: 'assets/flags/jm.png', name: 'Jamaica'),
  DefaultCountry(id: 84, code: 'jp', image: 'assets/flags/jp.png', name: 'Japan'),
  DefaultCountry(id: 85, code: 'jo', image: 'assets/flags/jo.png', name: 'Jordan'),
  DefaultCountry(id: 86, code: 'kz', image: 'assets/flags/kz.png', name: 'Kazakhstan'),
  DefaultCountry(id: 87, code: 'ke', image: 'assets/flags/ke.png', name: 'Kenya'),
  DefaultCountry(id: 88, code: 'ki', image: 'assets/flags/ki.png', name: 'Kiribati'),
  DefaultCountry(id: 89, code: 'kp', image: 'assets/flags/kp.png', name: "Korea (Democratic People's Republic of)"),
  DefaultCountry(id: 90, code: 'kr', image: 'assets/flags/kr.png', name: 'Korea, Republic of'),
  DefaultCountry(id: 91, code: 'kw', image: 'assets/flags/kw.png', name: 'Kuwait'),
  DefaultCountry(id: 92, code: 'kg', image: 'assets/flags/kg.png', name: 'Kyrgyzstan'),
  DefaultCountry(id: 93, code: 'la', image: 'assets/flags/la.png', name: "Lao People's Democratic Republic"),
  DefaultCountry(id: 94, code: 'lv', image: 'assets/flags/lv.png', name: 'Latvia'),
  DefaultCountry(id: 95, code: 'lb', image: 'assets/flags/lb.png', name: 'Lebanon'),
  DefaultCountry(id: 96, code: 'ls', image: 'assets/flags/ls.png', name: 'Lesotho'),
  DefaultCountry(id: 97, code: 'lr', image: 'assets/flags/lr.png', name: 'Liberia'),
  DefaultCountry(id: 98, code: 'ly', image: 'assets/flags/ly.png', name: 'Libya'),
  DefaultCountry(id: 99, code: 'li', image: 'assets/flags/li.png', name: 'Liechtenstein'),
  DefaultCountry(id: 100, code: 'lt', image: 'assets/flags/lt.png', name: 'Lithuania'),
  DefaultCountry(id: 101, code: 'lu', image: 'assets/flags/lu.png', name: 'Luxembourg'),
  DefaultCountry(id: 102, code: 'mg', image: 'assets/flags/mg.png', name: 'Madagascar'),
  DefaultCountry(id: 103, code: 'mw', image: 'assets/flags/mw.png', name: 'Malawi'),
  DefaultCountry(id: 104, code: 'my', image: 'assets/flags/my.png', name: 'Malaysia'),
  DefaultCountry(id: 105, code: 'mv', image: 'assets/flags/mv.png', name: 'Maldives'),
  DefaultCountry(id: 106, code: 'ml', image: 'assets/flags/ml.png', name: 'Mali'),
  DefaultCountry(id: 107, code: 'mt', image: 'assets/flags/mt.png', name: 'Malta'),
  DefaultCountry(id: 108, code: 'mh', image: 'assets/flags/mh.png', name: 'Marshall Islands'),
  DefaultCountry(id: 109, code: 'mr', image: 'assets/flags/mr.png', name: 'Mauritania'),
  DefaultCountry(id: 110, code: 'mu', image: 'assets/flags/mu.png', name: 'Mauritius'),
  DefaultCountry(id: 111, code: 'mx', image: 'assets/flags/mx.png', name: 'Mexico'),
  DefaultCountry(id: 112, code: 'fm', image: 'assets/flags/fm.png', name: 'Micronesia (Federated States of)'),
  DefaultCountry(id: 113, code: 'md', image: 'assets/flags/md.png', name: 'Moldova, Republic of'),
  DefaultCountry(id: 114, code: 'mc', image: 'assets/flags/mc.png', name: 'Monaco'),
  DefaultCountry(id: 115, code: 'mn', image: 'assets/flags/mn.png', name: 'Mongolia'),
  DefaultCountry(id: 116, code: 'me', image: 'assets/flags/me.png', name: 'Montenegro'),
  DefaultCountry(id: 117, code: 'ma', image: 'assets/flags/ma.png', name: 'Morocco'),
  DefaultCountry(id: 118, code: 'mz', image: 'assets/flags/mz.png', name: 'Mozambique'),
  DefaultCountry(id: 119, code: 'mm', image: 'assets/flags/mm.png', name: 'Myanmar'),
  DefaultCountry(id: 120, code: 'na', image: 'assets/flags/na.png', name: 'Namibia'),
  DefaultCountry(id: 121, code: 'nr', image: 'assets/flags/nr.png', name: 'Nauru'),
  DefaultCountry(id: 122, code: 'np', image: 'assets/flags/np.png', name: 'Nepal'),
  DefaultCountry(id: 123, code: 'nl', image: 'assets/flags/nl.png', name: 'Netherlands'),
  DefaultCountry(id: 124, code: 'nz', image: 'assets/flags/nz.png', name: 'New Zealand'),
  DefaultCountry(id: 125, code: 'ni', image: 'assets/flags/ni.png', name: 'Nicaragua'),
  DefaultCountry(id: 126, code: 'ne', image: 'assets/flags/ne.png', name: 'Niger'),
  DefaultCountry(id: 127, code: 'ng', image: 'assets/flags/ng.png', name: 'Nigeria'),
  DefaultCountry(id: 128, code: 'mk', image: 'assets/flags/mk.png', name: 'North Macedonia'),
  DefaultCountry(id: 129, code: 'no', image: 'assets/flags/no.png', name: 'Norway'),
  DefaultCountry(id: 130, code: 'om', image: 'assets/flags/om.png', name: 'Oman'),
  DefaultCountry(id: 131, code: 'pk', image: 'assets/flags/pk.png', name: 'Pakistan'),
  DefaultCountry(id: 132, code: 'pw', image: 'assets/flags/pw.png', name: 'Palau'),
  DefaultCountry(id: 133, code: 'pa', image: 'assets/flags/pa.png', name: 'Panama'),
  DefaultCountry(id: 134, code: 'pg', image: 'assets/flags/pg.png', name: 'Papua New Guinea'),
  DefaultCountry(id: 135, code: 'py', image: 'assets/flags/py.png', name: 'Paraguay'),
  DefaultCountry(id: 136, code: 'pe', image: 'assets/flags/pe.png', name: 'Peru'),
  DefaultCountry(id: 137, code: 'ph', image: 'assets/flags/ph.png', name: 'Philippines'),
  DefaultCountry(id: 138, code: 'pl', image: 'assets/flags/pl.png', name: 'Poland'),
  DefaultCountry(id: 139, code: 'pt', image: 'assets/flags/pt.png', name: 'Portugal'),
  DefaultCountry(id: 140, code: 'qa', image: 'assets/flags/qa.png', name: 'Qatar'),
  DefaultCountry(id: 141, code: 'ro', image: 'assets/flags/ro.png', name: 'Romania'),
  DefaultCountry(id: 142, code: 'ru', image: 'assets/flags/ru.png', name: 'Russian Federation'),
  DefaultCountry(id: 143, code: 'rw', image: 'assets/flags/rw.png', name: 'Rwanda'),
  DefaultCountry(id: 144, code: 'kn', image: 'assets/flags/kn.png', name: 'Saint Kitts and Nevis'),
  DefaultCountry(id: 145, code: 'lc', image: 'assets/flags/lc.png', name: 'Saint Lucia'),
  DefaultCountry(id: 146, code: 'vc', image: 'assets/flags/vc.png', name: 'Saint Vincent and the Grenadines'),
  DefaultCountry(id: 147, code: 'ws', image: 'assets/flags/ws.png', name: 'Samoa'),
  DefaultCountry(id: 148, code: 'sm', image: 'assets/flags/sm.png', name: 'San Marino'),
  DefaultCountry(id: 149, code: 'st', image: 'assets/flags/st.png', name: 'Sao Tome and Principe'),
  DefaultCountry(id: 150, code: 'sa', image: 'assets/flags/sa.png', name: 'Saudi Arabia'),
  DefaultCountry(id: 151, code: 'sn', image: 'assets/flags/sn.png', name: 'Senegal'),
  DefaultCountry(id: 152, code: 'rs', image: 'assets/flags/rs.png', name: 'Serbia'),
  DefaultCountry(id: 153, code: 'sc', image: 'assets/flags/sc.png', name: 'Seychelles'),
  DefaultCountry(id: 154, code: 'sl', image: 'assets/flags/sl.png', name: 'Sierra Leone'),
  DefaultCountry(id: 155, code: 'sg', image: 'assets/flags/sg.png', name: 'Singapore'),
  DefaultCountry(id: 156, code: 'sk', image: 'assets/flags/sk.png', name: 'Slovakia'),
  DefaultCountry(id: 157, code: 'si', image: 'assets/flags/si.png', name: 'Slovenia'),
  DefaultCountry(id: 158, code: 'sb', image: 'assets/flags/sb.png', name: 'Solomon Islands'),
  DefaultCountry(id: 159, code: 'so', image: 'assets/flags/so.png', name: 'Somalia'),
  DefaultCountry(id: 160, code: 'za', image: 'assets/flags/za.png', name: 'South Africa'),
  DefaultCountry(id: 161, code: 'ss', image: 'assets/flags/ss.png', name: 'South Sudan'),
  DefaultCountry(id: 162, code: 'es', image: 'assets/flags/es.png', name: 'Spain'),
  DefaultCountry(id: 163, code: 'lk', image: 'assets/flags/lk.png', name: 'Sri Lanka'),
  DefaultCountry(id: 164, code: 'sd', image: 'assets/flags/sd.png', name: 'Sudan'),
  DefaultCountry(id: 165, code: 'sr', image: 'assets/flags/sr.png', name: 'Suriname'),
  DefaultCountry(id: 166, code: 'se', image: 'assets/flags/se.png', name: 'Sweden'),
  DefaultCountry(id: 167, code: 'ch', image: 'assets/flags/ch.png', name: 'Switzerland'),
  DefaultCountry(id: 168, code: 'sy', image: 'assets/flags/sy.png', name: 'Syrian Arab Republic'),
  DefaultCountry(id: 169, code: 'tj', image: 'assets/flags/tj.png', name: 'Tajikistan'),
  DefaultCountry(id: 170, code: 'tz', image: 'assets/flags/tz.png', name: 'Tanzania, United Republic of'),
  DefaultCountry(id: 171, code: 'th', image: 'assets/flags/th.png', name: 'Thailand'),
  DefaultCountry(id: 172, code: 'tl', image: 'assets/flags/tl.png', name: 'Timor-Leste'),
  DefaultCountry(id: 173, code: 'tg', image: 'assets/flags/tg.png', name: 'Togo'),
  DefaultCountry(id: 174, code: 'to', image: 'assets/flags/to.png', name: 'Tonga'),
  DefaultCountry(id: 175, code: 'tt', image: 'assets/flags/tt.png', name: 'Trinidad and Tobago'),
  DefaultCountry(id: 176, code: 'tn', image: 'assets/flags/tn.png', name: 'Tunisia'),
  DefaultCountry(id: 177, code: 'tr', image: 'assets/flags/tr.png', name: 'Türkiye'),
  DefaultCountry(id: 178, code: 'tm', image: 'assets/flags/tm.png', name: 'Turkmenistan'),
  DefaultCountry(id: 179, code: 'tv', image: 'assets/flags/tv.png', name: 'Tuvalu'),
  DefaultCountry(id: 180, code: 'ug', image: 'assets/flags/ug.png', name: 'Uganda'),
  DefaultCountry(id: 181, code: 'ua', image: 'assets/flags/ua.png', name: 'Ukraine'),
  DefaultCountry(id: 182, code: 'ae', image: 'assets/flags/ae.png', name: 'United Arab Emirates'),
  DefaultCountry(id: 183, code: 'gb', image: 'assets/flags/gb.png', name: 'United Kingdom of Great Britain and Northern Ireland'),
  DefaultCountry(id: 184, code: 'us', image: 'assets/flags/us.png', name: 'United States of America'),
  DefaultCountry(id: 185, code: 'uy', image: 'assets/flags/uy.png', name: 'Uruguay'),
  DefaultCountry(id: 186, code: 'uz', image: 'assets/flags/uz.png', name: 'Uzbekistan'),
  DefaultCountry(id: 187, code: 'vu', image: 'assets/flags/vu.png', name: 'Vanuatu'),
  DefaultCountry(id: 188, code: 've', image: 'assets/flags/ve.png', name: 'Venezuela (Bolivarian Republic of)'),
  DefaultCountry(id: 189, code: 'vn', image: 'assets/flags/vn.png', name: 'Viet Nam'),
  DefaultCountry(id: 190, code: 'ye', image: 'assets/flags/ye.png', name: 'Yemen'),
  DefaultCountry(id: 191, code: 'zm', image: 'assets/flags/zm.png', name: 'Zambia'),
  DefaultCountry(id: 716, code: 'zw', image: 'assets/flags/zw.png', name: 'Zimbabwe'),
];
